server:
  port: 8123
spring:
  # redis配置
  redis:
    host: 192.168.31.136
    port: 6379
    password: 123456
    #    sentinel:
    #      master: mymaster
    #      nodes:
    #        - 192.168.31.136:26379
    #        - 192.168.31.136:26380
    #        - 192.168.31.136:26381
    #      password: 123456
    lettuce:
      pool:
        # 最大连接数量
        max-active: 100
        # 连接池最大阻塞等待时间
        max-wait: 5000ms
        # 最小空闲连接数
        min-idle: 0
        # 最大空闲连接数
        max-idle: 8
    database: 0
