server:
  port: 8942
dubbo:
  consumer:
    check: false
  protocol:
    name: dubbo
    port: 20881
  application:
    name: dubbo-zookeeper-order-service
  # 注册中心地址
  registry:
    address: zookeeper://192.168.31.136:2181?backup=192.168.31.136:2182,192.168.31.136:2183