server:
  port: 8941
dubbo:
  protocol:
    name: dubbo
    port: 20880
  application:
    name: dubbo-zookeeper-user-service
  # 注册中心地址
  registry:
    address: zookeeper://192.168.31.136:2181?backup=192.168.31.136:2182,192.168.31.136:2183