package cn.willian.coding.mybatis.domain;

import lombok.Data;

import java.util.Date;

@Data
public class OrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.id
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_id
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_id
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private Byte productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_number
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private Byte orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.create_time
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.update_time
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private Date updateTime;
}