package cn.willian.coding.mybatis.domain;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     * <p>
     * <p>
     * -- GETTER --
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     * @return the value of order.id
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_serial
     * <p>
     * <p>
     * -- GETTER --
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_serial
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     * @return the value of order.order_serial
     */
    private String orderSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_price
     * <p>
     * <p>
     * -- GETTER --
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_price
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     * @return the value of order.order_price
     */
    private BigDecimal orderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_status
     * <p>
     * <p>
     * -- GETTER --
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_status
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     * @return the value of order.order_status
     */
    private Byte orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     * <p>
     * <p>
     * -- GETTER --
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     * @return the value of order.create_time
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_time
     * <p>
     * <p>
     * -- GETTER --
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_time
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     * @return the value of order.update_time
     */
    private Date updateTime;
}