package cn.willian.coding.mybatis.domain;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class Product {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_type
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private Byte productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_price
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_img
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private String productImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_quantity
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private Byte productQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.update_time
     *
     * @mbg.generated Fri Nov 08 00:15:07 CST 2024
     */
    private Date updateTime;
}